name: "AI Code Review Action"
description: "Perform code reviews and comment on diffs using TogetherAI API.
  Available models:
  # meta-llama/Llama-3.3-70B-Instruct-Turbo                        $0.88
  # meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo-128K               $0.18
  # deepseek-ai/DeepSeek-V3                                        $1.25
  # deepseek-ai/DeepSeek-R1                                        $3.00 / $7.00
  # meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo                  $3.50"
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  TOGETHER_API_KEY:
    description: "TogetherAI API key for LLM access."
    required: true
  TOGETHER_API_MODEL:
    description: "TogetherAI model name (e.g., meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo, deepseek-ai/DeepSeek-V3)."
    required: false
    default: "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo"
  exclude:
    description: "Glob patterns to exclude files from the diff analysis"
    required: false
    default: "*.md,*.txt"
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "aperture"
  color: "green"
