name: "AI Code Review Action"
description: "Perform code reviews and comment on diffs using TogetherAI API.
  Available models:
  # meta-llama/Llama-3.3-70B-Instruct-Turbo                        $0.88
  # meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo-128K               $0.18
  # deepseek-ai/DeepSeek-V3                                        $1.25
  # deepseek-ai/DeepSeek-R1                                        $3.00 / $7.00
  # meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo                  $3.50"
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  TOGETHER_API_KEY:
    description: "TogetherAI API key for LLM access."
    required: true
  TOGETHER_API_MODEL:
    description: "TogetherAI model name (e.g., meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo, deepseek-ai/DeepSeek-V3)."
    required: false
    default: "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo"
  exclude:
    description: "Glob patterns to exclude files from the diff analysis"
    required: false
    default: "*.md,*.txt"
  enable_quality_metrics:
    description: "Enable code quality metrics analysis"
    required: false
    default: "true"
  quality_tools:
    description: "Comma-separated list of quality tools to run (eslint,pylint,etc)"
    required: false
    default: "auto"
  quality_config_paths:
    description: 'JSON mapping of tool names to config file paths (e.g., ''{"eslint":".eslintrc.custom.json","pylint":"custom_pylintrc"}'')'
    required: false
    default: "{}"
  ignore_rules:
    description: 'JSON mapping of tool names to arrays of rules to ignore (e.g., ''{"eslint":["no-console","no-unused-vars"],"pylint":["missing-docstring"]}'')'
    required: false
    default: "{}"
  ignore_files:
    description: "Additional glob patterns to exclude from quality analysis (comma-separated)"
    required: false
    default: ""
  fail_on_quality_issues:
    description: "Fail the action if quality issues are found"
    required: false
    default: "false"
  max_critical_issues:
    description: "Maximum number of critical issues allowed before failing the action (set to -1 to disable)"
    required: false
    default: "0"
  max_warning_issues:
    description: "Maximum number of warning issues allowed before failing the action (set to -1 to disable)"
    required: false
    default: "-1"
  max_suggestion_issues:
    description: "Maximum number of suggestion issues allowed before failing the action (set to -1 to disable)"
    required: false
    default: "-1"
  comment_mode:
    description: "How to handle comments: 'all' (comment on all issues), 'new' (only new issues), or 'unresolved' (new and unresolved issues)"
    required: false
    default: "all"
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "aperture"
  color: "green"
