name: "AI Code Review Action"
description: "Perform code reviews and comment on diffs using TogetherAI API."
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  TOGETHER_API_KEY:
    description: "TogetherAI API key for LLM access."
    required: true
  TOGETHER_API_MODEL:
    description: "TogetherAI model name (e.g., mistral-7b-instruct, llama2-70b-chat)."
    required: false
    default: "mistral-7b-instruct"
  exclude:
    description: "Glob patterns to exclude files from the diff analysis"
    required: false
    default: ""
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "aperture"
  color: "green"
