name: PR Review Bot
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run PR Review
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
          # Available models: Price per 1M tokens
            # meta-llama/Llama-3.3-70B-Instruct-Turbo                        $0.88
            # meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo-128K               $0.18
            # deepseek-ai/DeepSeek-V3                                        $1.25
            # deepseek-ai/DeepSeek-R1                                        $3.00 / $7.00
            # meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo                  $3.50
          TOGETHER_API_MODEL: 'meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo'  # or your preferred model
          exclude: '*.md,*.txt'  # optional: files to exclude
